version: '3'

services:
  bitcoind:
    image: docker.cryptology.com/blockchain/bitcoind:v4
    ports:
      - 8332:8332
    environment:
      - TESTNET=1
      - RPCUSER=bitcoinrpc
      - RPCPASSWORD=dev
      - DISABLEWALLET=0
      - UPNP=1
    volumes:
      - ~/.blockchain/bitcoin-testnet:/bitcoin/.bitcoin

  geth:
    image: ethereum/client-go:v1.8.1
    command: --rpc --rpcvhosts geth --debug --rpcaddr 0.0.0.0 --rpcport 8545 --networkid=4 # 1 for main net
    ports:
      - 8545:8545
    volumes:
      - ~/.blockchain/ethereum-rinkeby:/root/.ethereum

  db:
    image: postgres:9.6
    ports:
      - 7777:5432
    environment:
      - POSTGRES_PASSWORD=dev

  daemon:
    build: .
    command: python prod/full_runner.py
    volumes:
      - .:/app
    depends_on:
      - db
      - geth
      - bitcoind
    links:
      - btc-signer
      - eth-signer
    environment:
      - BITCOIND_URL=http://bitcoinrpc:dev@bitcoind:8332
      - ETHEREUMD_URL=http://geth:8545
      - DATABASE_URL=postgres://postgres:dev@db/postgres
      - CALLBACK_API_ROOT=http://cryptopay-internal-api.staging.cryptology.com/api/internal/cryptopay
      - BTC_SIGNER_URL=http://btc-signer:9000/btc
      - ETH_SIGNER_URL=http://eth-signer:9001/eth
      - SENTRY_DSN=https://d18fa496a45840d7ab19a24c94d8f450:d2559d05e4a64c0fbcff279a23578592@sentry.io/281239
      - PORT=8080
      - ETH_MASTERKEY_NAME=eth_test
      - ETH_MASTERKEY_PASSPHRASE=1qazxsw2
      - BTC_MASTERKEY_NAME=btc_test
      - PYTHONPATH=/app
      - SENTRY_DSN=
      - WORKERS=1
    ports:
      - 8080:8080

  btc-signer:
    depends_on:
      - db
    build: .
    command: python prod/btc_signer_runner.py
    ports:
      - 9000:9000
    volumes:
      - .:/app
    environment:
      - DATABASE_URL=postgres://postgres:dev@db/postgres
      - BITCOIND_URL=http://bitcoinrpc:dev@bitcoind:8332
      - BTC_MASTERKEY_NAME=btc_test
      - BTC_MASTERKEY_PASSPHRASE=1qazxsw2
      - WORKERS=1
      - SENTRY_DSN=https://d18fa496a45840d7ab19a24c94d8f450:d2559d05e4a64c0fbcff279a23578592@sentry.io/281239
      - PYTHONPATH=/app
      - SENTRY_DSN=
      - PORT=9000

  eth-signer:
    depends_on:
      - db
    build: .
    command: python prod/eth_signer_runner.py
    ports:
      - 9001:9001
    volumes:
      - .:/app
    environment:
      - DATABASE_URL=postgres://postgres:dev@db/postgres
      - ETHEREUMD_URL=http://geth:8545
      - ETH_MASTERKEY_NAME=eth_test
      - WORKERS=1
      - ETH_MASTERKEY_PASSPHRASE=1qazxsw2
      - SENTRY_DSN=https://d18fa496a45840d7ab19a24c94d8f450:d2559d05e4a64c0fbcff279a23578592@sentry.io/281239
      - PYTHONPATH=/app
      - SENTRY_DSN=
      - PORT=9001
