DROP SCHEMA BTC_PRIVATE CASCADE;
DROP SCHEMA BTC_PUBLIC CASCADE;
DROP SCHEMA ETH_PRIVATE CASCADE;
DROP SCHEMA ETH_PUBLIC CASCADE;
DROP SCHEMA COMMON_PUBLIC CASCADE;

CREATE SCHEMA BTC_PRIVATE;
CREATE SCHEMA BTC_PUBLIC;
CREATE SCHEMA ETH_PRIVATE;
CREATE SCHEMA ETH_PUBLIC;
CREATE SCHEMA COMMON_PUBLIC;

grant all PRIVILEGES on SCHEMA BTC_PRIVATE TO pg_user;
grant all PRIVILEGES on SCHEMA BTC_PUBLIC TO pg_user;
grant all PRIVILEGES on SCHEMA ETH_PRIVATE TO pg_user;
grant all PRIVILEGES on SCHEMA ETH_PUBLIC TO pg_user;
grant all PRIVILEGES on SCHEMA COMMON_PUBLIC TO pg_user;
